
{{- $secureSign := .Values.trustedArtifactSigner.secureSign -}}
{{- $issuer := "https://kubernetes.default.svc" -}}
{{- $auth := lookup "config.openshift.io/v1" "Authentication" "" "cluster" -}}
{{- if $auth -}}
  {{- /* Safely dig into the spec to find the serviceAccountIssuer */ -}}
  {{- if and $auth.spec (hasKey $auth.spec "serviceAccountIssuer") -}}
    {{- $issuer = $auth.spec.serviceAccountIssuer -}}
  {{- end -}}
{{- end -}}
---
apiVersion: rhtas.redhat.com/v1alpha1
kind: Securesign
metadata:
  namespace: {{ $secureSign.namespace }}
  name: {{ $secureSign.name }}
spec:
  fulcio:
    externalAccess:
      enabled: true
    certificate:
      commonName: {{ $secureSign.fulcio.certificate.commonName }}
      organizationEmail:  {{ $secureSign.fulcio.certificate.organizationEmail }}
      organizationName: {{ $secureSign.fulcio.certificate.organizationName }}
    config:
      OIDCIssuers:
        - Issuer: "{{ $secureSign.fulcio.oidc.issuerURL }}"
          IssuerURL: "{{ $secureSign.fulcio.oidc.issuerURL }}"
          ClientID: {{ $secureSign.fulcio.oidc.clientID }}
          Type: email
        - ClientID: sigstore
          Issuer: {{ $issuer }}
          IssuerURL: {{ $issuer }}
          Type: kubernetes
  rekor:
    externalAccess:
      enabled: true
    rekorSearchUI:
      enabled: true
    signer:
      kms: secret
  trillian:
    database:
      create: true
  tuf:
    externalAccess:
      enabled: true
    port: 80
    keys:
      - name: rekor.pub
      - name: ctfe.pub
      - name: fulcio_v1.crt.pem
